### ISSUE TITLE
Bugs: Function Keys

### ISSUE THREAD

**Issue by lubo** [gtbjj/x205ta#1] opened 2016-02-20 14:42 UTC
Bugs section states that function keys appear to be working out of the box on linux 4.3.3-2-ARCH. Actually, all function keys, except volume keys, do not work.

**Comment by savagezen** [comment] 2016-02-21 02:56
Thanks for the feedback @Kuci .  They are in fact working on my system which is using dwm-git and 4.4.1-2 kernel.

**Comment by lubo** [comment] 2016-02-21 08:02
Wow, this sounds promising ! Could share more info with me, please ? Which kernel do you use ? core/linux one or another ? Is it a custom build or a prebuilt one ? Any extra Xorg configuration/packages ?

**Comment by savagezen** [comment] 2016-02-21 19:07
I just use the vanilla kernel from `/core`, no custom `.config`.  I did mess with a lot of modules for the touchpad and WiFi though so something may have changed.  I'll push my outputs of `$ zcat /proc/config.gz` and `$ lsmod`  so you can fork, copy the respective outputs from your machine into the forked repo, and use git to check if something's changed.  Then go ahead and push to see what so we can have a look.

Here is my dwm [config.h](https://github.com/gtbjj/dotfiles/blob/master/dwm-config.h).  I do use `systemd-boot` which might make a difference on how / if certain modules are loaded.

I haven't done any special configuring with Xorg either, though I do use `xorg-xev` for key mapping and `xorg-xbacklight` for brightness control.  Does `xev` show anything interesting when you check if the function keys are mapped?

**Comment by lubo** [comment] 2016-02-21 19:57
Xen only reacts to FN + F{8,10,11,12} for me. DWM might be doing some magic. Do you have any configuration files in `/etc/modprobe.d/` or `/etc/modules-load.d/` ? Do you use any early KMS modules ?

**Comment by lubo** [comment] 2016-02-21 22:05
Ok, I've checked out your lsmod output and compared it with mine. Besides several crypto and networking modules, there is one that have catched my eye: `pwm_lpss`. It's Intel Low Power Subsystem PWM controller driver and what is interesting, I do use Arch Linux with linux 4.4.1-2 and I don't have this module precompiled. What is going on ?

P.S.: Please, write separate comments when you add new content, so I can get notifications. Thanks.

**Comment by savagezen** [comment] 2016-02-21 22:52
@Kuci 
I haven't done anything with `/etc/mkinitcpio.conf`.  There's nothing in `/etc/modules-load.d`, but in `/etc/modprobe.d` I have:

`alsa-base.conf` (this may be from an old config, as I know sound isn't working on this machine)

```
options snd_hda_intel index=0
options snd_hda_codec_hdmi index=1
```

`goodbye-btsdio.conf` (somewhere in the [Ubuntu hardware support thread for this machine](http://ubuntuforums.org/showthread.php?t=2254322) it was recommended to blacklist this so I have...)

```
# blacklist bluetooth module
blacklist btsdio
```

`sdhci.conf` (this is for the microSD slot to work properly)

```
# adjustment to make micro SD car reader work
options sdhci debug_quirks=0x8000
```

**Comment by savagezen** [comment] 2016-02-22 03:28
@Kuci

I removed the `pwm_lpss` module and the function keys still work.

I haven't checked a different wm (yet)

I haven't checked what removing the kernel line (that limits cstate to prevent freezing) does (yet)

**Comment by lubo** [comment] 2016-02-22 05:21
I use `intel_idle.max_cstate=1` too. Bootloader shouldn't make any difference since it only loads kernel into memory. Please, could you provide me with `xev` output and Xorg logs ?

**Comment by savagezen** [comment] 2016-02-25 04:11
@Kuci 
Xev:

```
KeyPress event, serial 32, synthetic NO, window 0x1a00001,
    root 0xd3, subw 0x1a00002, time 1337563, (40,44), root:(41,62),
    state 0x10, keycode 72 (keysym 0xffc3, F6), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

```

[Xorg Log on Pastebin](http://pastebin.com/zvuxRgJi) (Expires in 1 Week)

**Comment by lubo** [comment] 2016-02-25 23:08
Is that what xev outputs when you press Fn + F1-F12 ?

**Comment by savagezen** [comment] 2016-02-27 23:56
No, that is what it outputs when I press F6 by itself.

**Comment by lubo** [comment] 2016-02-28 11:48
Okay, but we don't care about F6 itself. There is no reason function keys themselves shouldn't work. What we care about are combinations of FN key and function keys. Do they work for you ?

**Comment by savagezen** [comment] 2016-03-01 02:37
Gotcha.  Okay, a quick check with xev showed me:
1.  There is no output in xev when I press FN, so this would suggest pressing FN + F1-12 is the same as just pressing F1-12 by itself.
2.  However FN does work for page scrolling (FN + PGDN / PGUP) as well as line hopping (FN + HOME / END) which I checked in nano and chromium.
3.  I use ALT as the MOD key in my window manager which works as intended with F1-12.  Here is a [paste of the xev output](http://pastebin.com/WMcEzY4y).

**Comment by lubo** [comment] 2016-03-01 06:34
I can confirm that FN + HOME / END / PGUP / PGDN works well. But I the fact that there is no output for FN + F1-F12 (except stated above) indicates that they are not being captured.

Well, I guess we understand each other now, so please, update BUGS, which I find misleading, I close the issue.

**Comment by savagezen** [comment] 2016-03-02 01:51
How does this excerpt look / sound to you?

##### Function Keys (F1 - F12):

> As of kernel 4.3.3-2-ARCH:
> - The `fn` key works as intended  with arrow keys (`pgup`, `pgdwn`, `home`, `end`).
> - `f1-12` work as shortcut keys inside `chromium`.
> - When using a [Window Manager](https://wiki.archlinux.org/index.php/window_manager) , such as [dwm](https://wiki.archlinux.org/index.php/Dwm), mapping `alt` as the `MOD` key allows for use of the function key functions (e.g. `fn`+`f5` to dim screen) when window manager is configured accordingly.
> - `fn` does not appear to get mapped when used in conjunction with `f1-12` as per the common use of function keys ([see dwm documentation](http://dwm.suckless.org/customisation/windows_key)).

**Comment by lubo** [comment] 2016-03-02 16:06
I would omit obvious things like point 2 and 3. I'm not really sure whether point 1 is also necessary to mention. In point 4 do not forget to mention which combinations currently work (FN + F{8,10,11,12}).

**Comment by savagezen** [comment] 2016-03-03 16:44
##### Function Keys (F1 - F12):

> As of kernel 4.3.3-2-ARCH:
> - The following key combinations work out of the box:  `fn` + `(pgup, pgdn, home, next f{8,10,11,12})`.
> - `fn` does not appear to get mapped correctly as a standard `MOD` key ([dwm documentation](http://dwm.suckless.org/customisation/windows_key)).  Alternatively, the use of `alt` in conjunction with function keys allows for use as intended.

**Comment by lubo** [comment] 2016-03-03 16:47
Much better. Thank you for collaboration.

**Closed as completed** 2016-03-03 16:49 UTC
